#!/usr/bin/env Rscript 

###############################################################
###############################################################
### Involvement of global warming on source and sink organs ###
### and effects on the quality of plum                      ###
###############################################################
###############################################################



### Problematic: Could the characteristics of source-sink relationships, potentially altered by global warming, have an impact 
### on the quality of the plums and their yields (fruit load) in 2006 (Ohata et al., 2017) ?



####################
### Import libraries in R

library(prettyR)
library(FactoMineR) # FactoMineR normalizes the data automatically
library("factoextra", lib.loc="~/R/win-library/3.5")
library(factoextra)

####################
### Loading the Dataset

setwd("~/data")
plum <- read.csv("plum.csv", header = T, sep = ';', dec = ',', row.names = 1)

####################
### Descriptive analysis

names(plum)
dim(plum)
str(plum) # to verify the type of variables

describe(plum[,-c(1,2)])
?describe
table(plum$FF,plum$FL) # contigency table
round(prop.table(table(plum$FF,plum$FL)),2)*100 # percentage table
round(prop.table(table(plum$FF,plum$FL)),2) # frequency

summary(plum)
summary(plum$AJ)

##################
### First tests

v<-c(1,2) # to take the 2 first columns
plum1<-plum[,v]
shapiro.test(plum1$FL) # to see if the variable considered here follows a normal distribution
shapiro.test(plum1$AAS)
shapiro.test(plum1$SDAS)
shapiro.test(plum1$AAB)
shapiro.test(plum1$SDAB)
shapiro.test(plum1$ALP)
shapiro.test(plum1$SDLP)
shapiro.test(plum1$FL.1)
shapiro.test(plum1$ColL)
shapiro.test(plum1$CurL)
shapiro.test(plum1$RL)
shapiro.test(plum1$PL)
shapiro.test(plum1$JF)
shapiro.test(plum1$FN)
shapiro.test(plum1$AWF)
shapiro.test(plum1$FF)
shapiro.test(plum1$SJ)
shapiro.test(plum1$pHJ)
shapiro.test(plum1$AJ)
bartlett.test(plum1) # to verify homoscedasticity (homogeneity of variances)
boxplot(plum1, main = "Graphical representation of the range of variables", col = "blue")

######################
### Principal Component Analysis

plumPCA<-read.csv("plumPCA.csv", header = T, sep = ";", dec = ",", row.names = 1) # to get the table without missing values
dim(plumPCA)
str(plumPCA)
require(FactoMineR)
plumPCA<-na.omit(plumPCA[,c(1,2)])
str(plumPCA)
head(plumPCA)
PCA(plumPCA)
?PCA
res.pca = PCA(plumPCA, scale.unit=TRUE, ncp=2, graph=TRUE) # to get the correlation circle
barplot(res.pca$eig[,1], main = "Eigenvalues", names.arg = 1:nrow(res.pca$eig)) # to get the eigenvalues
plot(res.pca, choix = "ind") # individuals factor map (PCA)
eig.val<-get_eigenvalue(res.pca)
fviz_eig(res.pca, addlabels = TRUE)
fviz.cos2(res.pca, choice = "var", axes = 1:2) # to create a barplot of the quality of representation (cos2) of individuals
fviz_pca_var(res.pca, col.var = "black")
fviz_pca_ind(res.pca, addEllipses = TRUE)

#################
### Hierarchical clustering

plumPCA<-na.omit(plumPCA[,-c(1,2)])
str(plumPCA)
res.pca = PCA(plumPCA, scale.unit=TRUE, ncp=2, graph=TRUE)
res.hcpc<-HCPC(res.pca, graph = FALSE)

fviz_dend(res.hcpc, cex = 0.7, palette = "jco", rect = TRUE, rect_fill = TRUE, rect_border = "jco", labels_track_height = 0.8) 
# to visualize the dendrogramme generated by the classification

fviz_cluster(res.hcpc, repel = TRUE, show.clust.cent = TRUE, palette = "jco", ggtheme = theme_minimal(), main = "Factor Map")
# to visualize the individuals and color them per group

plot(res.hcpc, choice = "3D.map")


head(res.hcpc$data.clust, 10) # to try to get the original data
res.hcpc$desc.var$quanti # to try to get the quantitative variables best describing each cluster
res.hcpc$desc.axes$quanti # to try to get the principal axis associated to clusters
res.hcpc$desc.ind$para # to try to get representative individuals of each group